version: '3'

services:
  backend:
    build: ./api
    container_name: backend

    volumes:
      - .:/api
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/api
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend

  frontend:
    build: ./nuxt3-app
    ports:
      - "80:3000"
    container_name: frontend
    depends_on:
      - backend

